#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

wmake libso craftsUdfsShared && \
wmake libso craftsSh2GasUdfs && \
wmake libso craftsSh2IonsGasUdfs && \
wmake libso craftsSh2IonsUdfs && \
wmake libso craftsTestUdfs

# ----------------------------------------------------------------- end-of-file
