#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

wmake libso craftsFoamLibrary && \
wmake libso craftsFlowModels && \
craftsUdfs/Allwmake

# ----------------------------------------------------------------- end-of-file
